# we are using 3.9.19 due to fixed versions of the packages in the requirements.txt
FROM aidamian/azureml-dev-slim

# Set the working directory
WORKDIR /workspace


# Install the SDK requirements
RUN pip install tensorflow

ENV BASE_SERVING_ENV_VERSION=0.2.1-full-tf

# Set the default command to bash (optional)
CMD ["bash"]
