# we are using 3.9.19 due to fixed versions of the packages in the requirements.txt
FROM aidamian/azureml-dev-slim

# Set the working directory
WORKDIR /workspace

RUN pip install torch --index-url https://download.pytorch.org/whl/cpu

ENV BASE_SERVING_ENV_VERSION=0.2.1-full-th

# Set the default command to bash (optional)
CMD ["bash"]
