services:
  devcontainer-mlflow:
    image: aidamian/azureml-dev-slim
    hostname: dev-cont-mlflow
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    # ...

  devcontainer-tf:
    image: aidamian/azureml-dev-tf
    hostname: dev-cont-tf
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    # ...
