FROM aidamian/azureml-dev-slim

WORKDIR /app

COPY ./src .

ENV APP_DEBUG=true
ENV SERVING_ENV_VERSION=serve-mlflow-0.2.7
ENV AIMETHICA_APP_NAME=mflsrv

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5051"]
