FROM aidamian/azureml-dev-slim

WORKDIR /app

COPY ./src .
COPY ./models_mflow ./models

ENV SERVING_ENV_VERSION=serve-mlflow-0.1.1

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5051"]
