name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.23
  - pip=21.2.4
  - scikit-learn=1.2
  - scipy=1.7
  - pandas=1.3
  - Jinja2<3.1
  - Werkzeug==2.2
  - itsdangerous==2.0.1
  - pip:
    - inference-schema[numpy-support]==1.3.0
    - mlflow==2.8.0
    - mlflow-skinny==2.8.0
    - azureml-mlflow==1.51.0
    - psutil>=5.8,<5.9
    - tqdm>=4.59,<4.60
    - ipykernel~=6.0
    - tensorflow
    - matplotlib
    - scipy
    - joblib
    - azureml-inference-server-http
    - azureml-core
