name: Build endpoints containers

on: 
  push:
    paths:
      - 'serving_v1/**'  # Specify path to your directory

jobs:
  build-and-push-py-test-image:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and Push
        run: |
          cd serving_v1/
          chmod +x build-all.sh  # Ensure the script is executable
          ./build-all.sh   
